export const Fonts = {
    DisplayRegular: 'SFUIDisplay-Regular',
    DisplayBold: 'SFUIDisplay-Bold',
    DisplayLight: 'SFUIDisplay-Light',
    DisplaySemiBold: 'SFProDisplay-SemiBold',
    DisplayCompactSemiBold: 'SFCompactDisplay-SemiBold',
    DisplayCompactBold: 'SFCompactDisplay-Bold',
    DisplayCompactLight: 'SFCompactDisplay-Light',
    DisplayCompactRegular: 'SFCompactDisplay-Regular',
    PFEncoreSansPro: 'PFEncoreSansPro-Light',
    TextRegular: 'SFUIText-Regular',
    TextBold: 'SFUIText-Bold',
    TextLight: 'SFUIText-Light',
    TextCompactLight: 'SFCompactText-Light',
    TextSemiBold: 'SFProText-SemiBold',
}
